In [95]:
import pandas as pd
import pandas_gbq
#importer les donnees
query = "SELECT * FROM `sous-nos-pieds.data_gouv.dicrim_gaspar_2026-08-19_raw`"
project_id = "my-first-project-502010" #ici il faut mettre SON PROPRE projet (pour s'assurer que "la personne qui paye" - s'il fallait payer, soit nous et pas la personne qui a cree le projet)
df_dicrim = pandas_gbq.read_gbq(query, project_id = project_id )
#On importe les données de bigquery et plus depuis un CSV
#df_dicrim = pd.read_csv("/content/dicrim_gaspar_2026-08-19.csv", delimiter=";")
#print(df_dicrim)

Downloading: 100%|██████████|

In [96]:
df_dicrim.head()

  cod_commune       lib_commune dat_publi_dicrim
0       10280  Pars-lès-Romilly              NaT
1       29060         Gouesnach              NaT
2        None              None              NaT
3       70145  Chaux-la-Lotière              NaT
4       33170            Fontet              NaT

In [98]:
df_dicrim.isnull().sum()

cod_commune           2
lib_commune           2
dat_publi_dicrim    136
dtype: int64

In [100]:
df_dicrim.dropna(subset=['cod_commune'])

     cod_commune                 lib_commune          dat_publi_dicrim
0          10280            Pars-lès-Romilly                       NaT
1          29060                   Gouesnach                       NaT
3          70145            Chaux-la-Lotière                       NaT
4          33170                      Fontet                       NaT
5          31182                  Fenouillet                       NaT
...          ...                         ...                       ...
9875       76322           Le Grand-Quevilly 2025-12-31 01:00:00+00:00
9876       21632            Thorey-en-Plaine 2026-12-31 01:00:00+00:00
9877       24296                  Mouleydier 2026-12-31 01:00:00+00:00
9878       36188       Saint-Cyran-du-Jambot 2026-12-31 01:00:00+00:00
9879       42267  Saint-Nizier-sous-Charlieu 2026-12-31 01:00:00+00:00

[9878 rows x 3 columns]

In [101]:
df_dicrim = df_dicrim.dropna(subset=['cod_commune'])

In [102]:
df_dicrim

     cod_commune                 lib_commune          dat_publi_dicrim
0          10280            Pars-lès-Romilly                       NaT
1          29060                   Gouesnach                       NaT
3          70145            Chaux-la-Lotière                       NaT
4          33170                      Fontet                       NaT
5          31182                  Fenouillet                       NaT
...          ...                         ...                       ...
9875       76322           Le Grand-Quevilly 2025-12-31 01:00:00+00:00
9876       21632            Thorey-en-Plaine 2026-12-31 01:00:00+00:00
9877       24296                  Mouleydier 2026-12-31 01:00:00+00:00
9878       36188       Saint-Cyran-du-Jambot 2026-12-31 01:00:00+00:00
9879       42267  Saint-Nizier-sous-Charlieu 2026-12-31 01:00:00+00:00

[9878 rows x 3 columns]

In [94]:
#df_dicrim[df_dicrim["cod_commune"]== "00nan"]

In [83]:
# Supprimer les lignes aux index 7181 et 7961
#df_dicrim = df_dicrim.drop(index=[7181, 7961])

#print("Lignes 7181 et 7961 supprimées !")
#display(df_dicrim.head(3))

Lignes 0 et 1 supprimées !

  cod_commune     lib_commune dat_publi_dicrim
2       95523  la roche-guyon       1999-01-01
3       95394   mery-sur-oise       1999-01-01
4       95392          meriel       1999-01-01

In [103]:
df_dicrim['cod_commune'] = df_dicrim['cod_commune'].astype(str).str.split('.').str[0].str.zfill(5)

In [104]:
df_dicrim.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9878 entries, 0 to 9879
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   cod_commune       9878 non-null   object
 1   lib_commune       9878 non-null   object
 2   dat_publi_dicrim  9744 non-null   datetime64[us, UTC]
dtypes: datetime64[us, UTC](1), object(2)
memory usage: 308.7+ KB

In [105]:
if 'dat_publi_dicrim' in df_dicrim.columns:
    df_dicrim['dat_publi_dicrim'] = pd.to_datetime(df_dicrim['dat_publi_dicrim'], errors='coerce')

In [106]:
df_dicrim

     cod_commune                 lib_commune          dat_publi_dicrim
0          10280            Pars-lès-Romilly                       NaT
1          29060                   Gouesnach                       NaT
3          70145            Chaux-la-Lotière                       NaT
4          33170                      Fontet                       NaT
5          31182                  Fenouillet                       NaT
...          ...                         ...                       ...
9875       76322           Le Grand-Quevilly 2025-12-31 01:00:00+00:00
9876       21632            Thorey-en-Plaine 2026-12-31 01:00:00+00:00
9877       24296                  Mouleydier 2026-12-31 01:00:00+00:00
9878       36188       Saint-Cyran-du-Jambot 2026-12-31 01:00:00+00:00
9879       42267  Saint-Nizier-sous-Charlieu 2026-12-31 01:00:00+00:00

[9878 rows x 3 columns]

In [107]:
display(df_dicrim.head(12))

   cod_commune            lib_commune dat_publi_dicrim
0        10280       Pars-lès-Romilly              NaT
1        29060              Gouesnach              NaT
3        70145       Chaux-la-Lotière              NaT
4        33170                 Fontet              NaT
5        31182             Fenouillet              NaT
6        17452           La Tremblade              NaT
7        70348  Moffans-et-Vacheresse              NaT
8        70327                 Malans              NaT
9        64538             Uhart-Cize              NaT
10       57701                   Vaux              NaT
11       42170                Perreux              NaT
12       37174                Nouâtre              NaT

In [108]:
# Remplacement des accents et passage en minuscules en Python (équivalent de ton code SQL)
df_dicrim['lib_commune'] = (
    df_dicrim['lib_commune']
    .astype(str)
    .str.lower()
    .str.replace('é', 'e', regex=False)
    .str.replace('è', 'e', regex=False)
    .str.replace('ê', 'e', regex=False)
    .str.replace('à', 'a', regex=False)
    .str.replace('â', 'a', regex=False)
    .str.replace('ï', 'i', regex=False)
    .str.replace('î', 'i', regex=False)
    .str.replace('ô', 'o', regex=False)
)

print("Nettoyage des accents et minuscules effectué avec succès !")
display(df_dicrim[['lib_commune']].head())

Nettoyage des accents et minuscules effectué avec succès !

        lib_commune
0  pars-les-romilly
1         gouesnach
3  chaux-la-lotiere
4            fontet
5        fenouillet

In [109]:
df_dicrim

     cod_commune                 lib_commune          dat_publi_dicrim
0          10280            pars-les-romilly                       NaT
1          29060                   gouesnach                       NaT
3          70145            chaux-la-lotiere                       NaT
4          33170                      fontet                       NaT
5          31182                  fenouillet                       NaT
...          ...                         ...                       ...
9875       76322           le grand-quevilly 2025-12-31 01:00:00+00:00
9876       21632            thorey-en-plaine 2026-12-31 01:00:00+00:00
9877       24296                  mouleydier 2026-12-31 01:00:00+00:00
9878       36188       saint-cyran-du-jambot 2026-12-31 01:00:00+00:00
9879       42267  saint-nizier-sous-charlieu 2026-12-31 01:00:00+00:00

[9878 rows x 3 columns]

In [ ]:
# Convertir d'abord en format datetime (si ce n'est pas déjà fait)
df_dicrim['dat_publi_dicrim'] = pd.to_datetime(df_dicrim['dat_publi_dicrim'], errors='coerce')

In [112]:
# Enlever l'heure en remettant le temps à 00:00:00 (garde le type datetime)
df_dicrim['dat_publi_dicrim'].dt.date

0              NaT
1              NaT
3              NaT
4              NaT
5              NaT
           ...
9875    2025-12-31
9876    2026-12-31
9877    2026-12-31
9878    2026-12-31
9879    2026-12-31
Name: dat_publi_dicrim, Length: 9878, dtype: object

In [113]:
df_dicrim['dat_publi_dicrim'] = df_dicrim['dat_publi_dicrim'].dt.date

In [114]:
df_dicrim

     cod_commune                 lib_commune dat_publi_dicrim
0          10280            pars-les-romilly              NaT
1          29060                   gouesnach              NaT
3          70145            chaux-la-lotiere              NaT
4          33170                      fontet              NaT
5          31182                  fenouillet              NaT
...          ...                         ...              ...
9875       76322           le grand-quevilly       2025-12-31
9876       21632            thorey-en-plaine       2026-12-31
9877       24296                  mouleydier       2026-12-31
9878       36188       saint-cyran-du-jambot       2026-12-31
9879       42267  saint-nizier-sous-charlieu       2026-12-31

[9878 rows x 3 columns]

In [115]:
df_dicrim.isnull().sum()
df_dicrim[df_dicrim.isnull().any(axis=1)]

    cod_commune                 lib_commune dat_publi_dicrim
0         10280            pars-les-romilly              NaT
1         29060                   gouesnach              NaT
3         70145            chaux-la-lotiere              NaT
4         33170                      fontet              NaT
5         31182                  fenouillet              NaT
..          ...                         ...              ...
131       76131                  la bouille              NaT
132       76591  saint-jacques-sur-darnetal              NaT
133       76391                    la londe              NaT
134       76116                        boos              NaT
135       78123       carrieres-sous-poissy              NaT

[134 rows x 3 columns]

In [117]:
df_dicrim

     cod_commune                 lib_commune dat_publi_dicrim
0          10280            pars-les-romilly              NaT
1          29060                   gouesnach              NaT
3          70145            chaux-la-lotiere              NaT
4          33170                      fontet              NaT
5          31182                  fenouillet              NaT
...          ...                         ...              ...
9875       76322           le grand-quevilly       2025-12-31
9876       21632            thorey-en-plaine       2026-12-31
9877       24296                  mouleydier       2026-12-31
9878       36188       saint-cyran-du-jambot       2026-12-31
9879       42267  saint-nizier-sous-charlieu       2026-12-31

[9878 rows x 3 columns]

In [118]:
#J'exporte ma table modifié à Bigquery
pandas_gbq.to_gbq(
    df_dicrim, #le df a exporter
    destination_table="sous-nos-pieds.staging.dicrim_gaspar_staging", #projet.dataset.nom_de_la_nouvelle_table_a_creer
    project_id="my-first-project-502010", #ici il faut mettre SON PROPRE projet (pour s'assurer que "la personne qui paye" - s'il fallait payer, soit nous et pas le project owner)
    if_exists="replace"
)